version: "3.8"

services:
  postgresql:
    image: postgres:15.3-alpine3.18
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: amiga-traca
    volumes:
      - ./scripts-sql/:/docker-entrypoint-initdb.d/

  sebo-amiga-traca-jasper:
    image: sebo-amiga-traca-jasper
    container_name: sebo-amiga-traca-jasper
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/amiga-traca
    depends_on:
      - postgresql
    ports:
      - "8080:8080"